### ISSUE TITLE
@CurrentIteration support

### ISSUE THREAD

**Issue by rolfik** [xantari/Seq.App.Azure.DevOps#4]
Hello,
today I have tried Your Seq to Azure DevOps app and it works fine.
Thank You

Now I can create bugs from Seq events, but the problem is I cannot include them to current iteration because @CurrentIteration does not work in Iteration field.
Without this, bugs end in backlog and will not be actively investigated.
Could You please add @CurrentIteration support?

Marek

**Comment by xantari** [comment]
Doesn't appear that @CurrentIteration is supported in the Azure DevOps API. That is a macro command that apparently is only available via the UI, and not via the API as indicated here:

https://stackoverflow.com/questions/54257736/create-a-workitem-after-build-fails-with-current-on-iterationpath

You'll probably need to default them to your backlog, and then during your backlog grooming sessions move them to the appropriate iteration you will be tackling the problem.

**Comment by rolfik** [comment]
Then to support it, another extra Azure DevOps API call to get current iteration would be required.

In our case, I create bugs from application crashes logged into Seq.

**Comment by xantari** [comment]
Closing, don't think we need to support this. Recommended approach is to put bugs in backlog, and then triage them them to determine what iteration you intend to tackle them on based on resource availability in your team.
